# Generated by Django 3.1.6 on 2021-02-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Video Title', max_length=200),
        ),
    ]
